# These are supported funding model platforms

github: 
patreon: ebankoff
open_collective: 
ko_fi: ko-fi.com/ebankoff
tidelift: 
community_bridge: 
liberapay:
issuehunt: 
otechie: 
lfx_crowdfunding: 
custom: 
